package org.work.domen.com;

public enum Coms {
    SIGN_IN,
    SIGN_UP,

    ADD_NEW_USER,
    UPDATE_USER_PASSWORD,
    GET_ALL_USERS,
    UPDATE_USER,
    DELETE_USER,

    ADD_NEW_SEGMENT,
    DELETE_SEGMENT,
    GET_ALL_SEGMENT,
    UPDATE_SEGMENT,

    ADD_NEW_PROJECT,
    UPDATE_PROJECT,
    DELETE_PROJECT,
    GET_ALL_PROJECT,


    GET_ALL_MARKED_PROJECT,
    GET_ALL_NOT_MARKED_PROJECT

}
